module Test.Coverage exposing
    ( track
    , EdgeCoverage, resetEdgeCoverage, getEdgeCoverage
    )

{-| External API for coverage tooling.

These functions will not do anything on their own. Coverage tooling later
patches their JS definitions with code that actually does something.

Edge coverage related functions are later used by the fuzz test runner for
coverage-guided fuzzing:

  - At the beginning of each run of a fuzz test, the runner calls `resetEdgeCoverage`.
  - At the end of each run, the runner calls `getEdgeCoverage`, analyzes the
    results (did the input find a novel execution path through the codebase?)
    and if needed, updates the corpus of interesting inputs.
  - Random inputs are either generated randomly, or generated by combining
    entries from the corpus.

Thus if the codebase hasn't been instrumented by coverage tooling and the
functions in this module haven't been patched, the corpus will never be
populated and fuzzers will revert to random generation.

Examples of coverage tooling implementations compatible with this module:

  - [Janiczek/elm-coverage-tooling](https://github.com/Janiczek/elm-coverage-tooling)

@docs track
@docs EdgeCoverage, resetEdgeCoverage, getEdgeCoverage

-}

import Test.Coverage.EdgeHitCounts exposing (EdgeHitCounts)
import Test.Coverage.SeenHits exposing (SeenHits)


type alias EdgeCoverage =
    { edgeHitCounts : EdgeHitCounts
    , seenHits : SeenHits
    }


{-| Calls to this function are injected by coverage tooling next to various expressions.

Example:

     True
     -->
     let _ = Test.Coverage.track 1253583 in True

When patched, increments the point's "visited" count in a global JS counter.

-}
track : Int -> ()
track pointId =
    ()


{-| When patched, resets edge coverage counter to its zero state.
-}
resetEdgeCoverage : () -> ()
resetEdgeCoverage () =
    ()


{-| When patched, returns edge coverage data (codebase execution paths).
-}
getEdgeCoverage : () -> EdgeCoverage
getEdgeCoverage () =
    -- Dummy meaningless values. This code will be patched after compile-time!
    { edgeHitCounts = EdgeHitCounts
    , seenHits = SeenHits
    }
