module Test.Coverage exposing
    ( EdgeCoverage, EdgeCoverageJs, getEdgeCoverage
    , track
    , resetEdgeCoverage, getEdgeCoverageJs
    )

{-| External API for coverage tooling.

Many of these functions will not do anything on their own. Coverage tooling
later patches their JS definitions with code that actually does something.

Edge coverage related functions are later used by the fuzz test runner for
coverage-guided fuzzing:

  - At the beginning of each run of a fuzz test, the runner calls `resetEdgeCoverage`.
  - At the end of each run, the runner calls `getEdgeCoverage`, analyzes the
    results (did the input find an interesting execution path through the codebase?)
    and if needed, updates the corpus of interesting inputs.
  - Random inputs are either generated randomly, or generated by combining
    entries from the corpus.

If the codebase hasn't been instrumented by coverage tooling and the functions
in this module haven't been patched, the corpus will never be populated
and fuzzers will revert to random generation.

Examples of coverage tooling implementations compatible with this module:

  - [Janiczek/elm-coverage-tooling](https://github.com/Janiczek/elm-coverage-tooling)

@docs EdgeCoverage, EdgeCoverageJs, getEdgeCoverage


# Patched functions

@docs track

@docs resetEdgeCoverage, getEdgeCoverageJs

-}

import Test.Coverage.EdgeHitCounts exposing (EdgeHitCounts, EdgeHitCountsJs)
import Test.Coverage.SeenHits exposing (SeenHits, SeenHitsJs)


type alias EdgeCoverageJs =
    { edgeHitCounts : EdgeHitCountsJs
    , seenHits : SeenHitsJs
    }


type alias EdgeCoverage =
    { edgeHitCounts : EdgeHitCounts
    , seenHits : SeenHits
    }


{-| Calls to this function are injected by coverage tooling next to various expressions.

Example:

     True
     -->
     let _ = Test.Coverage.track 1253583 in True

When patched, increments the point's "visited" count in a global JS counter.

-}
track : Int -> ()
track pointId =
    ()


{-| When patched, resets edge coverage counter to its zero state.
-}
resetEdgeCoverage : () -> ()
resetEdgeCoverage () =
    ()


{-| When patched, returns edge coverage data (codebase execution paths).
-}
getEdgeCoverageJs : () -> EdgeCoverageJs
getEdgeCoverageJs () =
    -- Dummy meaningless values. This code will be patched after compile-time!
    { edgeHitCounts = EdgeHitCounts
    , seenHits = SeenHits
    }


getEdgeCoverage : () -> EdgeCoverage
getEdgeCoverage () =
    let
        js =
            getEdgeCoverageJs ()
    in
    { edgeHitCounts = EdgeHitCounts.fromJs js.edgeHitCounts
    , seenHits = SeenHits.fromJs js.seenHits
    }
